"""add phone number

Revision ID: 423c4bf80f86
Revises: c8c6781373b5
Create Date: 2022-10-03 14:07:19.185920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '423c4bf80f86'
down_revision = 'c8c6781373b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
